#Database
POSTGRES_SQL_USERNAME: shopping_cart_db_user
POSTGRES_SQL_PASSWORD: p
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: shopping_cart_db

#Server
SERVER_PORT: 8085
ACTIVE_PROFILE: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

spring:
  config.activate.on-profile: dev

  flyway:
    clean-disabled: false
    clean-on-validation-error: true # Tabellen werden beim Validierungsfehler gelöscht
    create-schemas: false
    tablespace: shopping_cart_tablespace

  application:
    name: shoppingCart-service

  graphql:
    graphiql.enabled: true
    schema.printer.enabled: true


app:
  password: p

logging:
  file.name: ./logs/application.log
  logback.rollingpolicy:
    file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.gz
    max-file-size: 100KB
    max-history: 3
  pattern:
    console: "%clr(%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5level) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n%wEx"
    file: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5level ${PID:- } --- [%thread] %-40.40logger{39} : %m%n%wEx"
  threshold:
    console: trace
    file: trace
  level:
    com.gentle.store.shopping.cart: trace
    org.apache.catalina.loader.WebappClassLoaderBase: info
    org.springframework.boot.availability.ApplicationAvailabilityBean: debug
    org.springframework.boot.devtools.autoconfigure.ConditionEvaluationDeltaLoggingListener: warn
    #org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean: debug
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
    org.springframework.web.service.invoker.PathVariableArgumentResolver: trace
    org.springframework.web.service.invoker.RequestHeaderArgumentResolver: trace
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.security.core.userdetails.User: error
    org.springframework.security.web.server.authorization.AuthorizationWebFilter: trace
    io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor: error

    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

    org.hibernate.SQL_SLOW: warn
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

    io.qameta.allure.AllureLifecycle: fatal
    org.junit.jupiter.engine.descriptor.TestInstanceLifecycleUtils: warn
    org.springframework.boot.test.context.SpringBootTestContextBootstrapper: warn
    org.springframework.test.context.support.AbstractContextLoader: warn
    org.springframework.test.context.support.AnnotationConfigContextLoaderUtils: warn
    org.springframework.test.context.support.DefaultTestContextBootstrapper: warn